### PR TITLE
Fixed missing dep for "make -j".  From Hans T. fix of ISSSort.

### PR DESCRIPTION
**Pull request by inkdot7**
Fix analog to https://github.com/ISOLDESolenoidalSpectrometer/ISSSort/pull/18

### CODE REVIEW

**Comment by lpgaff** [comment]
I'm holding off on this, because during testing of that in ISSSort, it was giving strange behaviour of the dictionary file names and locations on some systems.

**Comment by inkdot7** [comment]
@lpgaff Could you elaborate on the issues seen with `make -j` in ISSSort so we can try to fix those?  @hanstt

**Comment by lpgaff** [comment]
Sorry, just coming back to this. With the changes to the Makefile, it seems that the ROOT dictionaries are compiled with strange names, like the suffix is added twice to the filename. It might be that different versions of make interpret the extra argument in different ways?

**Comment by inkdot7** [comment]
I could reproduce the error.  The issue was that with those two dependencies `$(ROOTDICT)` would be called twice, and when called for the `_rdict.pcm` file it generated one with `_rdict_rdict.pcm` name.  It actually makes both the .cc file and then `_rdict.pcm` file at once, so the needed thing is to tell that the .pcm depends on the `.cc`.

If it works for you to, I can make a MR for ISSSort as well, unless you beat me to it :-)

**Pull request merged**
